# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      bun-deps:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      cargo-deps:
        applies-to: version-updates
        update-types:
          - minor
          - patch
