# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      oxc:
        applies-to: version-updates
        patterns:
          - "oxfmt"
          - "oxlint"
          - "oxlint-tsgolint"
      bun-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
